# [START gae_python37_cloudsql_config]
runtime: python37

env_variables:
  CLOUD_SQL_USERNAME: root
  CLOUD_SQL_PASSWORD: 123
  CLOUD_SQL_DATABASE_NAME: mydoctor
  CLOUD_SQL_CONNECTION_NAME: tugasmd:us-central1:tugasbesar
  JWT_SECRET:
# [END gae_python37_cloudsql_config]
